# Generated by Django 2.2.4 on 2019-11-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
